name: Close issues marked 'fixed-pending-release' upon a release.
on:
  release:
    types: [published]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Close issues marked 'fixed-pending-release' upon a release.
        uses: gcampbell-msft/fixed-pending-release@0.0.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}