name: Comment on Pull Requests included in Release
on:
  release:
    types: [published]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Comment on Pull Requests
        uses: gcampbell-msft/fixed-pending-release@0.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}